---
- name: install java-11-openjdk-devel for elasticsearch
  dnf: 
    name: java-11-openjdk-devel*
    state: present
- name: mkdir elasticsearch
  shell: mkdir -p /opt/elasticsearch
- name: installl elasticsearch for x86_64 system
  block: 
  - name: get elasticsearch from official website
    shell: wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.16-linux-x86_64.tar.gz --no-check-certificate
    args: 
      chdir: /root/
  - name: unzip tar.gz
    shell: tar -xzvf elasticsearch-7.17.16-linux-x86_64.tar.gz -C /opt/elasticsearch --strip-components 1
    args: 
      chdir: /root/
  when: ansible_architecture == "x86_64"
- name: install elasticsearch for aarch64 system
  block: 
  - name: get elasticsearch from official website
    shell: wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.16-linux-aarch64.tar.gz --no-check-certificate
    args: 
      chdir: /root/
  - name: unzip tar.gz
    shell: tar -xzvf elasticsearch-7.17.16-linux-aarch64.tar.gz -C /opt/elasticsearch --strip-components 1
    args: 
      chdir: /root/
  when: ansible_architecture == "aarch64"
- name: add elastic user
  shell: groupadd elastic && useradd elastic -g elastic
- name: chown /opt/elasticsearch/
  shell: chown -R elastic:elastic /opt/elasticsearch/
- name: change es config
  template: src=templates/elasticsearch/elasticsearch.yml.j2 dest=/opt/elasticsearch/config/elasticsearch.yml
- name: change jvms
  lineinfile: 
    path: /opt/elasticsearch/config/jvm.options
    regexp: '^#?-Xms*'
    line: '-Xms4g'
    backrefs: yes
- name: change jvmx
  lineinfile: 
    path: /opt/elasticsearch/config/jvm.options
    regexp: '^#?-Xmx*'
    line: '-Xmx4g'
    backrefs: yes
- name: start  elasticsearch
  shell: nohup /opt/elasticsearch/bin/elasticsearch -d &