---
- name: mkdir kibana
  shell: mkdir -p /opt/kibana
- name: install kibana for x86_64 system 
  block: 
  - name: get kibana from official website
    shell: wget https://artifacts.elastic.co/downloads/kibana/kibana-7.17.16-linux-x86_64.tar.gz --no-check-certificate
    args: 
      chdir: /root/
  - name: unzip tar.gz
    shell: tar -xzvf kibana-7.17.16-linux-x86_64.tar.gz -C /opt/kibana --strip-components 1
    args: 
      chdir: /root/
  when: ansible_architecture == "x86_64"
- name: install kibana for aarch64 system
  block: 
  - name: get kibana from official website
    shell: wget https://artifacts.elastic.co/downloads/kibana/kibana-7.17.16-linux-aarch64.tar.gz --no-check-certificate
    args: 
      chdir: /root/
  - name: unzip tar.gz
    shell: tar -xzvf kibana-7.17.16-linux-aarch64.tar.gz -C /opt/kibana --strip-components 1
    args: 
      chdir: /root/
  when: ansible_architecture == "aarch64"
- name: change es config
  template: src=templates/kibana/kibana.yml.j2 dest=/opt/kibana/config/kibana.yml
- name: start kibana
  shell: nohup /opt/kibana/bin/kibana & 
  become: yes
  become_user: elastic