---
- name: mkdir elasticsearch
  shell: mkdir -p /opt/Elastic/Agent
- name: installl elastic agent for x86_64 system
  block: 
  - name: get elastic agent from official website
    shell: wget https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.17.16-linux-x86_64.tar.gz --no-check-certificate
    args: 
      chdir: /root/
  - name: unzip tar.gz
    shell: tar -xzvf elastic-agent-7.17.16-linux-x86_64.tar.gz -C /opt/Elastic/Agent --strip-components=1
    args: 
      chdir: /root/
  when: ansible_architecture == "x86_64"
- name: install elastic agent for aarch64 system
  block: 
  - name: get elastic agent from official website
    shell: wget https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.17.16-linux-arm64.tar.gz --no-check-certificate
    args: 
      chdir: /root/
  - name: unzip tar.gz
    shell: tar -xzvf elastic-agent-7.17.16-linux-arm64.tar.gz -C /opt/Elastic/Agent --strip-components=1
    args: 
      chdir: /root/
  when: ansible_architecture == "aarch64"
- name: change config file for elastic-agent
  template: src=templates/elk-agent/elastic-agent.yml.j2 dest={{ pilotgo_elk_agent_config }}
- name: change config file for elastic-agent fleet
  template: src=templates/elk-agent/fleet.yml.j2 dest={{ pilotgo_elk_agent_fleet_config }}